import streamlit as st
import pandas as pd
import joblib

from recomendation import (
    currency_conversion,
    budget_filter,
    ram_filter,
    storage_filter,
    brand_filter,
    touch_filter,
    top_rec,
)

model = joblib.load("Laptop_Price_Predictor/models/laptop_price_model.pkl")
model_columns = joblib.load("Laptop_Price_Predictor/models/model_columns.pkl")

df = pd.read_csv("Laptop_Price_Predictor/data/cleaned_laptop_data.csv")
df = currency_conversion(df)

st.set_page_config(page_title="Laptop Price Predictor", layout="wide")

st.sidebar.title("💻 Laptop Price Predictor")
st.sidebar.write("Predict and recommend laptops using machine learning.")

st.sidebar.subheader("📌 Project Information")
st.sidebar.write("🤖 Model : Multiple Linear Regression")
st.sidebar.write("📈 R² Score : 0.8205")
st.sidebar.write("💾 Dataset : 2160 Laptop Records")
st.sidebar.write("💱 Currency : Euro & INR")

st.title("💻 Laptop Price Predictor")
st.write(
    "Estimate laptop prices and get laptop recommendations based on your requirements."
)

st.divider()

st.subheader("📝 Laptop Price Prediction")

col1, col2, col3 = st.columns(3)

with col1:
    status = st.selectbox("Laptop Status", sorted(df["Status"].dropna().unique()))
    brand = st.selectbox("Brand", sorted(df["Brand"].dropna().unique()))
    cpu = st.selectbox("Processor", sorted(df["CPU"].dropna().unique()))

with col2:
    ram = st.selectbox("RAM (GB)", sorted(df["RAM"].dropna().unique()))
    storage = st.selectbox("Storage (GB)", sorted(df["Storage"].dropna().unique()))
    storage_type = st.selectbox(
        "Storage Type", sorted(df["Storage_Type"].dropna().unique())
    )

with col3:
    gpu = st.selectbox("Graphics Card", sorted(df["GPU"].dropna().unique()))
    screen = st.selectbox("Screen Size", sorted(df["Screen"].dropna().unique()))
    touch = st.selectbox("Touch Screen", sorted(df["Touch"].dropna().unique()))

input_data = pd.DataFrame(
    {
        "Status": [status],
        "Brand": [brand],
        "CPU": [cpu],
        "RAM": [ram],
        "Storage": [storage],
        "Storage_Type": [storage_type],
        "GPU": [gpu],
        "Screen": [screen],
        "Touch": [touch],
    }
)

st.subheader("⚙️ Selected Configuration")
st.dataframe(input_data, use_container_width=True)

input_encoded = pd.get_dummies(input_data, drop_first=True)
input_encoded = input_encoded.reindex(columns=model_columns, fill_value=0)

euro_to_inr = 110

predict_button = st.button("🔍 Predict Laptop Price")

if predict_button:
    predicted_price_euro = model.predict(input_encoded)[0]
    predicted_price_inr = predicted_price_euro * euro_to_inr

    st.subheader("📊 Prediction Result")

    result_col1, result_col2 = st.columns(2)

    with result_col1:
        st.metric("Estimated Price in Euro", f"€{predicted_price_euro:.2f}")

    with result_col2:
        st.metric("Estimated Price in INR", f"₹{predicted_price_inr:,.2f}")

    st.info(
        "This prediction is an estimated value generated by the trained machine learning model."
    )

st.divider()

st.subheader("💡 Laptop Recommendation")

budget = st.number_input("Enter Your Budget (INR)", min_value=10000, value=80000)
ram = st.selectbox("Minimum RAM (GB)", sorted(df["RAM"].dropna().unique()))
storage = st.selectbox("Minimum Storage (GB)", sorted(df["Storage"].dropna().unique()))
brand = st.selectbox("Preferred Brand", sorted(df["Brand"].dropna().unique()))
touch = st.selectbox("Touch Screen Preference", sorted(df["Touch"].dropna().unique()))

rec_button = st.button("Show Recommended Laptops")

if rec_button:
    rec_df = budget_filter(df, budget)
    rec_df = ram_filter(rec_df, ram)
    rec_df = storage_filter(rec_df, storage)
    rec_df = brand_filter(rec_df, brand)
    rec_df = touch_filter(rec_df, touch)

    if len(rec_df) == 0:
        st.warning(
            "No laptop found. Try increasing your budget or changing your requirements."
        )
    else:
        rec_df = top_rec(rec_df)

        st.subheader("Top Recommended Laptops")

        st.dataframe(
            rec_df[
                [
                    "Laptop",
                    "Brand",
                    "CPU",
                    "RAM",
                    "Storage",
                    "Storage_Type",
                    "GPU",
                    "Screen",
                    "Touch",
                    "Price_Euro",
                    "Price_INR",
                ]
            ],
            use_container_width=True,
        )
